In [186]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd

pd.options.mode.chained_assignment = None  # default='warn'

In [137]:
txt_file = open('text.txt', "r")
data_text = txt_file.read()
text = [c.lower() for c in data_text]
N = len(text)

char, occ = np.unique(text, return_counts=True)
prob = occ / N
n = len(char)
print("Number of characters is =",n)

Number of characters is = 39

In [119]:
# dataframe with characters asindex name 
de = pd.DataFrame(data=prob, index=char, columns=["prob"])

In [166]:
# dataframe with char as column
# code = np.zeros(len(char))
code = np.chararray(len(char))
code = code.decode('utf-8')
df = pd.DataFrame.from_dict({"char":char, "prob":prob, "code": code})

# to perform the Huffman coding we have to work on sorted probability
df = df.sort_values(by=['prob'], ascending=False, ignore_index=True)
df.head()

  char      prob code
0       0.224531
1    e  0.081260
2    t  0.060729
3    o  0.058335
4    a  0.054877

Faccio un ciclo sugli indici del dataframe partendo dal pi√π probabile e gli assegno (in una terza colonna) al primo 0 e al secondo 1. Poi a mano a mano continuo 
faccio un ciclo interno per aggiungere a tutti gli i+1 elementi il bit 1.
for(j in range(len(dataframe) -1))

In [139]:
zero = '0' ; one = '1'
print(type(zero) )
print(type((df['code'][0])) )
print(df['code'][0] )

<class 'str'>
<class 'str'>

In [203]:
# To reset the dataframe
df = pd.DataFrame.from_dict({"char":char, "prob":prob, "code": code})
df = df.sort_values(by=['prob'], ascending=False, ignore_index=True)
n = 5
for i in range(n):
    df['code'][i] = df['code'][i] + zero

    for j in range(i,n-1):
        if(i==n):
            break
        df['code'][j+1] = df['code'][j+1] + one

In [206]:
df.head(5)

  char      prob   code
0       0.224531      0
1    e  0.081260     10
2    t  0.060729    110
3    o  0.058335   1110
4    a  0.054877  11110

In [221]:
df = pd.DataFrame.from_dict({"char":char, "freq":occ ,"prob":prob, "code": code})
df = df.sort_values(by=['freq'], ascending=True, ignore_index=False)

In [222]:
np.array(df.freq)

array([    3,    19,    20,    52,    58,    76,    93,   176,   242,
         269,   279,   333,   589,   635,   672,   765,  1238,  1276,
        1395,  1420,  1480,  1588,  1628,  1750,  2106,  2172,  2798,
        3182,  4442,  4579,  4698,  5040,  5041,  5101,  5824,  6191,
        6445,  8624, 23829], dtype=int64)

In [235]:
import string
from collections import Counter
class NodeTree(object):
    def __init__(self, left=None, right=None):
        self.left = left
        self.right = right

    def children(self):
        return self.left, self.right

    def __str__(self):
        return self.left, self.right


def huffman_code_tree(node, binString=''):
    '''
    Function to find Huffman Code
    '''
    if type(node) is str:
        return {node: binString}
    (l, r) = node.children()
    d = dict()
    d.update(huffman_code_tree(l, binString + '0'))
    d.update(huffman_code_tree(r, binString + '1'))
    return d


def make_tree(nodes):
    '''
    Function to make tree
    :param nodes: Nodes
    :return: Root of the tree
    '''
    while len(nodes) > 1:
        (key1, c1) = nodes[-1]
        (key2, c2) = nodes[-2]
        nodes = nodes[:-2]
        node = NodeTree(key1, key2)
        nodes.append((node, c1 + c2))
        nodes = sorted(nodes, key=lambda x: x[1], reverse=True)
    return nodes[0][0]

In [242]:
df = pd.DataFrame.from_dict({"char":char, "freq":occ})
df = df.sort_values(by=['freq'], ascending=True, ignore_index=False)
# print(freq)
node = make_tree(df.values.tolist())
encoding = huffman_code_tree(node)

# for i in encoding:
    # print(f'{i} : {encoding[i]}')

encoding_df = pd.DataFrame.from_dict(encoding, orient='index', columns=['Huffman Code'])

In [244]:
encoding_df

     Huffman Code
r            0000
s            0001
n            0010
i            0011
b          010000
j      0100010000
x      0100010001
?       010001001
;        01000101
k         0100011
d           01001
a            0101
p          011000
f          011001
c          011010
,          011011
o            0111
t            1000
l           10010
y          100110
.         1001110
z      1001111000
[    100111100100
&   1001111001010
]   1001111001011
q     10011110011
!       100111101
:       100111110
-       100111111
w          101000
m          101001
\n          10101
h           10110
u          101110
'        10111100
v        10111101
g         1011111
              110
e             111